# Generated by Django 5.0 on 2023-12-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="image",
            field=models.ImageField(default=None, upload_to="images"),
        ),
    ]
