# Generated by Django 5.0 on 2023-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_blogs_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="dislikes",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(upload_to="images"),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="likes",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
