# Generated by Django 5.0 on 2023-12-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_alter_blogs_dislikes_alter_blogs_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
